version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      dockerfile: ./dockerfile
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    

